apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

configMapGenerator:
  - name: dsc-hgui-webapi-mongodb-init
    files:
      - params/init-db.js
  - name: dsc-hgui-webapi-config
    literals:
      - database=dsc-hgui
      - collection=hgui
patches:
 - path: patches/webapi.deployment.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: dsc-hgui-webapi