/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xschmidtd@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hgui_webapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type DefaultAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// Test - Test endpoint
	Test(ctx *gin.Context)
}

// partial implementation of DefaultAPI - all functions must be implemented in add on files
type implDefaultAPI struct {
}

func newDefaultAPI() DefaultAPI {
	return &implDefaultAPI{}
}

func (this *implDefaultAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodGet, "/test", this.Test)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // Test - Test endpoint
// func (this *implDefaultAPI) Test(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
