/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: xschmidtd@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hgui_webapi

type Test200Response struct {

	Message string `json:"message,omitempty"`
}
