/*
 * Hospital guidance API
 *
 * Hospital guidance API
 *
 * API version: 1.0.0
 * Contact: xschmidtd@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hgui_webapi

import (
	"time"
)

type GuidanceEntry struct {

	// Guidance ID
	Id string `json:"id"`

	// Name of the patient
	PatientName string `json:"patientName"`

	// Title of the guidance
	Title string `json:"title"`

	// Ambulance ID
	AmbulanceId string `json:"ambulanceId"`

	// Description of the guidance
	Description string `json:"description"`

	// Severity of the guidance
	Severity string `json:"severity"`

	// Date and time of the guidance creation
	CreatedAt time.Time `json:"createdAt"`

	// Response from the hospital doctor
	Response string `json:"response,omitempty"`

	Email string `json:"email,omitempty"`

	PhoneNumber string `json:"phoneNumber,omitempty"`
}
