/*
 * Hospital guidance API
 *
 * Hospital guidance API
 *
 * API version: 1.0.0
 * Contact: xschmidtd@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hgui_webapi

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newHospitalGuidanceListAPI()
    api.addRoutes(group)
  }
  
}